[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Network RPC endpoints - hardcoded public RPCs
[rpc_endpoints]
worldchain = "https://worldchain-mainnet.g.alchemy.com/public"
celo = "https://forno.celo.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
