[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Worldchain network configuration
[rpc_endpoints]
worldchain = "${WORLDCHAIN_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
